/*
 * This file is part of mpv.
 * SPDX-License-Identifier: LGPL-2.1-or-later
 */

#include "shaders.h"

const char dlssnr_shader_source[] =
"cbuffer Settings : register(b0) {\n"
"    uint2 sourceSize; uint2 processingSize;\n"
"    uint2 textureSize; uint planarInput; uint reserved0;\n"
"    float4 rowR; float4 rowG; float4 rowB;\n"
"    float2 chromaOffset; float multiplier; float saturation;\n"
"    float lightness; float shadow; float glow; float reserved1;\n"
"    float4 lumaWeights;\n"
"};\n"
"Texture2D<float4> a : register(t0);\n"
"Texture2D<float4> b : register(t1);\n"
"Texture2D<float4> c : register(t2);\n"
"RWTexture2D<float4> destination : register(u0);\n"
"SamplerState smoothSampler : register(s0);\n"
"\n"
"[numthreads(16, 16, 1)]\n"
"void convert_source(uint3 id : SV_DispatchThreadID) {\n"
"    uint2 p = id.xy;\n"
"    if (any(p >= sourceSize)) return;\n"
"    float3 rgb;\n"
"    if (planarInput != 0) {\n"
"        float y = a.Load(int3(p, 0)).r;\n"
"        float2 uv = b.SampleLevel(smoothSampler,\n"
"            (float2(p) + 0.5 + chromaOffset) / float2(textureSize), 0).rg;\n"
"        float4 value = float4(y, uv, 1);\n"
"        rgb = float3(dot(rowR, value), dot(rowG, value), dot(rowB, value));\n"
"    } else {\n"
"        rgb = a.Load(int3(p, 0)).rgb;\n"
"    }\n"
"    destination[p] = float4(rgb, 1);\n"
"}\n"
"\n"
"float reduction_weight(float distance) {\n"
"    float x = abs(distance);\n"
"    if (x < 0.00001) return 1;\n"
"    if (x >= 2) return 0;\n"
"    float angle = 3.141592653589793 * x;\n"
"    return (sin(angle) / angle) * (sin(angle * 0.5) / (angle * 0.5));\n"
"}\n"
"\n"
"[numthreads(16, 16, 1)]\n"
"void reduce_horizontal(uint3 id : SV_DispatchThreadID) {\n"
"    uint2 p = id.xy;\n"
"    if (p.x >= processingSize.x || p.y >= sourceSize.y) return;\n"
"    if (sourceSize.x == processingSize.x) {\n"
"        destination[p] = a.Load(int3(p, 0));\n"
"        return;\n"
"    }\n"
"    float ratio = float(sourceSize.x) / processingSize.x;\n"
"    float position = (p.x + 0.5) * ratio - 0.5;\n"
"    float3 sum = 0; float total = 0;\n"
"    int first = int(ceil(position - 2 * ratio));\n"
"    int last = int(floor(position + 2 * ratio));\n"
"    for (int x = first; x <= last; x++) {\n"
"        float weight = reduction_weight((x - position) / ratio);\n"
"        int sampleX = clamp(x, 0, int(sourceSize.x) - 1);\n"
"        sum += a.Load(int3(sampleX, p.y, 0)).rgb * weight;\n"
"        total += weight;\n"
"    }\n"
"    destination[p] = float4(sum / max(total, 0.00001), 1);\n"
"}\n"
"\n"
"[numthreads(16, 16, 1)]\n"
"void reduce_vertical(uint3 id : SV_DispatchThreadID) {\n"
"    uint2 p = id.xy;\n"
"    if (any(p >= processingSize)) return;\n"
"    if (sourceSize.y == processingSize.y) {\n"
"        destination[p] = float4(saturate(a.Load(int3(p, 0)).rgb), 1);\n"
"        return;\n"
"    }\n"
"    float ratio = float(sourceSize.y) / processingSize.y;\n"
"    float position = (p.y + 0.5) * ratio - 0.5;\n"
"    float3 sum = 0; float total = 0;\n"
"    int first = int(ceil(position - 2 * ratio));\n"
"    int last = int(floor(position + 2 * ratio));\n"
"    for (int y = first; y <= last; y++) {\n"
"        float weight = reduction_weight((y - position) / ratio);\n"
"        int sampleY = clamp(y, 0, int(sourceSize.y) - 1);\n"
"        sum += a.Load(int3(p.x, sampleY, 0)).rgb * weight;\n"
"        total += weight;\n"
"    }\n"
"    destination[p] = float4(saturate(sum / max(total, 0.00001)), 1);\n"
"}\n"
"\n"
"[numthreads(16, 16, 1)]\n"
"void prepare_residual(uint3 id : SV_DispatchThreadID) {\n"
"    uint2 p = id.xy;\n"
"    if (any(p >= processingSize)) return;\n"
"    float3 original = a.Load(int3(p, 0)).rgb;\n"
"    float3 change = b.Load(int3(p, 0)).rgb - original;\n"
"    float baseline = dot(original, lumaWeights.rgb);\n"
"    float luminance = dot(change, lumaWeights.rgb);\n"
"    float3 chroma = change - luminance;\n"
"    float darkRegion = 1 - smoothstep(0.08, 0.4, baseline);\n"
"    float brightRegion = smoothstep(0.45, 0.95, baseline);\n"
"    float adjusted = luminance + min(luminance, 0) * darkRegion * (shadow - 1)\n"
"                              + max(luminance, 0) * brightRegion * (glow - 1);\n"
"    destination[p] = float4(multiplier *\n"
"        (adjusted * lightness + chroma * saturation), 0);\n"
"}\n"
"\n"
"float cubic_weight(float distance) {\n"
"    float x = abs(distance);\n"
"    if (x >= 2) return 0;\n"
"    if (x < 1) return ((1.5 * x - 2.5) * x) * x + 1;\n"
"    return ((-0.5 * x + 2.5) * x - 4) * x + 2;\n"
"}\n"
"\n"
"[numthreads(16, 16, 1)]\n"
"void compose_residual(uint3 id : SV_DispatchThreadID) {\n"
"    uint2 outputPosition = id.xy;\n"
"    if (any(outputPosition >= ((sourceSize + 1) & ~1u))) return;\n"
"    uint2 p = min(outputPosition, sourceSize - 1);\n"
"    float3 change = 0;\n"
"    if (all(sourceSize == processingSize)) {\n"
"        change = b.Load(int3(p, 0)).rgb;\n"
"    } else {\n"
"        float2 position = (float2(p) + 0.5) * float2(processingSize)\n"
"                          / float2(sourceSize) - 0.5;\n"
"        int2 base = int2(floor(position));\n"
"        [unroll] for (int y = -1; y <= 2; y++) {\n"
"            float wy = cubic_weight(base.y + y - position.y);\n"
"            [unroll] for (int x = -1; x <= 2; x++) {\n"
"                int2 samplePosition = clamp(base + int2(x, y), int2(0, 0),\n"
"                                    int2(processingSize) - 1);\n"
"                float wx = cubic_weight(base.x + x - position.x);\n"
"                change += b.Load(int3(samplePosition, 0)).rgb * wx * wy;\n"
"            }\n"
"        }\n"
"    }\n"
"    destination[outputPosition] = float4(a.Load(int3(p, 0)).rgb + change, 1);\n"
"}\n";
